-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 22:55:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FerreteriaBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FerreteriaBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FerreteriaBD` DEFAULT CHARACTER SET utf8 ;
USE `FerreteriaBD` ;

-- -----------------------------------------------------
-- Table `FerreteriaBD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaBD`.`Usuario` (
  `Codigo` NVARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Clave` VARCHAR(30) NOT NULL,
  `Correo` VARCHAR(50) NULL,
  `Rol` VARCHAR(20) NOT NULL,
  `EstaActivo` TINYINT NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaBD`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaBD`.`Cliente` (
  `Identidad` VARCHAR(20) NOT NULL,
  `NombreCliente` VARCHAR(70) NOT NULL,
  `Direccion` VARCHAR(100) NULL,
  `Email` VARCHAR(50) NULL,
  `Telefono` VARCHAR(15) NULL,
  PRIMARY KEY (`Identidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaBD`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaBD`.`Producto` (
  `Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Existencia` INT NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `FechaEntrada` DATETIME NOT NULL,
  `Imagen` LONGBLOB NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaBD`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaBD`.`Factura` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdentidadCliente` VARCHAR(20) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `CodigoUsuario` NVARCHAR(20) NOT NULL,
  `ISV` DECIMAL(8,2) NULL,
  `Descuento` DECIMAL(8,2) NULL,
  `SubTotal` DECIMAL(8,2) NULL,
  `Total` DECIMAL(8,2) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FerreteriaBD`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FerreteriaBD`.`DetalleFactura` (
  `IdFactura` INT NOT NULL,
  `CodigoProducto` INT NOT NULL,
  `Precio` DECIMAL(8,2) NULL,
  `Cantidad` INT NULL,
  `Total` DECIMAL(8,2) NULL)
ENGINE = InnoDB;

INSERT INTO `FerreteriaBD`.`usuarios` VALUES (1,'Ony Reina','reinaony@unah.hn','prueba','Administrador',1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
